# URL de la base de datos (asegúrate de que el puerto 3306 sea el tuyo)
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_reservaciones?serverTimezone=UTC

# Tu usuario y contraseña de MySQL (Cámbialos si usas otros)
spring.datasource.username=root
spring.datasource.password=qwerty00

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect